### ISSUE TITLE
 Expected exceptions are unexpected

### ISSUE THREAD

**Issue by Qurcaivel** [DanikKul/LabsBot#2]
Some functions that may raise exceptions like _int_ are not located in the try block, but  it will be because there are an expected input error that should be ignored by the system and may be logged or messaged back to the user.

**Comment by DanikKul** [comment]
DO YOU KNOW HOW PYTHON EXCEPTION WORK?

**Comment by Qurcaivel** [comment]
открой

**Comment by DanikKul** [comment]
хватит issue засирать

**Comment by DanikKul** [comment]
я и так уже полкода перелопатил
