### ISSUE TITLE
Wrong time check creates blind zone of queuing

### ISSUE THREAD

**Issue by Qurcaivel** [DanikKul/LabsBot#5]
https://github.com/DanikKul/LabsBot/blob/59fb01a1eee18c9507cc87084da78063aa39ad57/main.py#LL87C2-L87C2

When admin creates queue it should require full-format datetime or transform %H:%M time format into full-format timestamp closest to planned time.

**Comment by DanikKul** [comment]
Replaced HH:MM with DD-MM-YYYY HH:MM
